"""tambah preferensi ui dan role kasir

Revision ID: 82f8a9c5fccb
Revises: cba2a1b5c7a3
Create Date: 2026-05-03 05:17:04.067531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f8a9c5fccb'
down_revision: Union[str, Sequence[str], None] = 'cba2a1b5c7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tms_epod_history', sa.Column('qty_delivered', sa.Float(), nullable=True))
    op.add_column('tms_epod_history', sa.Column('qty_return', sa.Float(), nullable=True))
    op.add_column('tms_epod_history', sa.Column('qty_damaged', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('auto_advance', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('sound_alert', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('data_density', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'data_density')
    op.drop_column('users', 'sound_alert')
    op.drop_column('users', 'auto_advance')
    op.drop_column('tms_epod_history', 'qty_damaged')
    op.drop_column('tms_epod_history', 'qty_return')
    op.drop_column('tms_epod_history', 'qty_delivered')
    op.drop_column('delivery_orders', 'created_at')
    # ### end Alembic commands ###
